apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: user-circuit-breaker
  namespace: microservices
spec:
  host: user-service
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 3
      interval: 5s
      baseEjectionTime: 30s
      maxEjectionPercent: 50
