apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: product-service-dr
  namespace: microservices
spec:
  host: product-service
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
